psexec.exe \\lab-c116-02 c:\Users\Administrator\Desktop\unity\unity.cmd -accepteula
psexec.exe \\lab-c116-03 c:\Users\Administrator\Desktop\unity\unity.cmd -accepteula
psexec.exe \\lab-c116-04 c:\Users\Administrator\Desktop\unity\unity.cmd -accepteula
psexec.exe \\lab-c116-05 c:\Users\Administrator\Desktop\unity\unity.cmd -accepteula
psexec.exe \\lab-c116-06 c:\Users\Administrator\Desktop\unity\unity.cmd -accepteula
psexec.exe \\lab-c116-07 c:\Users\Administrator\Desktop\unity\unity.cmd -accepteula
psexec.exe \\lab-c116-08 c:\Users\Administrator\Desktop\unity\unity.cmd -accepteula
psexec.exe \\lab-c116-09 c:\Users\Administrator\Desktop\unity\unity.cmd -accepteula
psexec.exe \\lab-c116-10 c:\Users\Administrator\Desktop\unity\unity.cmd -accepteula
psexec.exe \\lab-c116-11 c:\Users\Administrator\Desktop\unity\unity.cmd -accepteula
psexec.exe \\lab-c116-12 c:\Users\Administrator\Desktop\unity\unity.cmd -accepteula
psexec.exe \\lab-c116-13 c:\Users\Administrator\Desktop\unity\unity.cmd -accepteula
psexec.exe \\lab-c116-14 c:\Users\Administrator\Desktop\unity\unity.cmd -accepteula
psexec.exe \\lab-c116-15 c:\Users\Administrator\Desktop\unity\unity.cmd -accepteula
psexec.exe \\lab-c116-16 c:\Users\Administrator\Desktop\unity\unity.cmd -accepteula
psexec.exe \\lab-c116-17 c:\Users\Administrator\Desktop\unity\unity.cmd -accepteula
psexec.exe \\lab-c116-18 c:\Users\Administrator\Desktop\unity\unity.cmd -accepteula
psexec.exe \\lab-c116-19 c:\Users\Administrator\Desktop\unity\unity.cmd -accepteula
psexec.exe \\lab-c116-20 c:\Users\Administrator\Desktop\unity\unity.cmd -accepteula
psexec.exe \\lab-c116-21 c:\Users\Administrator\Desktop\unity\unity.cmd -accepteula
psexec.exe \\lab-c116-22 c:\Users\Administrator\Desktop\unity\unity.cmd -accepteula
psexec.exe \\lab-c116-23 c:\Users\Administrator\Desktop\unity\unity.cmd -accepteula
psexec.exe \\lab-c116-24 c:\Users\Administrator\Desktop\unity\unity.cmd -accepteula
psexec.exe \\lab-c116-25 c:\Users\Administrator\Desktop\unity\unity.cmd -accepteula
psexec.exe \\lab-c116-26 c:\Users\Administrator\Desktop\unity\unity.cmd -accepteula
psexec.exe \\lab-c116-27 c:\Users\Administrator\Desktop\unity\unity.cmd -accepteula
psexec.exe \\lab-c116-28 c:\Users\Administrator\Desktop\unity\unity.cmd -accepteula
Pause
